Contact default
9a24f0/openversum pull request #4
Opened 2023-02-15 17:40 UTC by tuancandongsang

2023-02-16 05:39 UTC, 9a24f0 requested changes
Also please replace function `changeState` with actual state and store in `generalStore`

2023-02-16 05:39 UTC, 9a24f0 commented on src/lib/components/UI/InputCurrency.svelte
> +<label for="price" class="block text-sm font-medium text-gray-700">{label}ffffffffffff</label>
What is this?

2023-02-16 05:39 UTC, 9a24f0 commented on src/lib/components/UI/InputNumber.svelte
> +<label for="price" class="block text-sm font-medium text-gray-700">{label}sssssssssss</label>
Also this?

2023-02-16 05:39 UTC, 9a24f0 commented on src/lib/components/UI/PrimaryButton.svelte
> +		class="w-40 px-9 py-3 bg-green-500 rounded-3xl text-sm font-semibold text-white cursor-pointer hover:opacity-80"
We should keep conditionally rendering button like previous version. Please revert to older one and add styling base on the case we need.

2023-02-16 05:39 UTC, 9a24f0 commented on src/lib/components/contact/ContactDefault.svelte
> +				class="mt-1 focus:ring-cyan-500 focus:border-cyan-500 block w-full shadow-sm border-darkblue rounded-md"
Nice shadow catch!

2023-02-16 05:39 UTC, 9a24f0 commented on src/lib/components/contact/ContactMain.svelte
> +	class="font-medium not-italic semi-bold flex flex-col gap-6 text-[45px] font-poppins text-white"
`<nav>` tag has only one prop is class, please have them inline with the tag

2023-02-16 05:39 UTC, 9a24f0 commented on src/lib/components/contact/ContractNavigation.svelte
> +</nav>
I don't quite understand this. Please elaborate

2023-02-16 05:39 UTC, 9a24f0 commented on src/routes/contact/+page.svelte
> +     </div>
We use tab spacing, please convert those spaces to tab

2023-02-16 16:44 UTC, 9a24f0 commented on src/lib/components/UI/PrimaryButton.svelte
> +		class="w-40 px-9 py-3 bg-green-500 rounded-3xl text-sm font-semibold text-white cursor-pointer hover:opacity-80"
should be like this:
```
class="{`${
			buttonSize === 'xs'
				? 'px-2.5 py-1.5 text-xs font-medium'
				: buttonSize === 'sm'
				? 'px-3 py-2 text-sm leading-4 font-medium'
				: buttonSize === 'md'
				? 'px-4 py-2 text-sm font-medium'
				: buttonSize === 'lg'
				? 'px-4 py-2 text-base font-medium'
				: buttonSize === 'xl'
				? 'px-6 py-3 text-base font-medium'
				: ''
		} w-40 px-9 py-3 bg-green-500 rounded-3xl text-sm font-semibold text-white cursor-pointer hover:opacity-80"
		```

2023-02-16 16:47 UTC, tuancandongsang commented on src/lib/components/UI/InputCurrency.svelte
> +<label for="price" class="block text-sm font-medium text-gray-700">{label}ffffffffffff</label>
oke

2023-02-17 16:23 UTC, 9a24f0 approved these changes
Thank you!

2023-02-17 16:25 UTC, merged